Add support for retrieving carrier names
emostar/flutter-libphonenumber pull request #13
Opened 2020-01-22 12:03 UTC by edwinnyawoli

2020-04-02 06:57 UTC, emostar commented
This is a great start, but it should have the matching iOS implementation. Would you be able to add that in @edwinnyawoli ?

2020-04-14 19:25 UTC, edwinnyawoli commented
Implementing it in iOS is going to prove difficult because with Android there was [this](https://github.com/google/libphonenumber/tree/0dd0f034ff89d00f4d67cee8d8b88b27be4931bd/java/carrier) package that made it very simple and straightforward. I haven't seen anything like that in the [libPhoneNumber-iOS](https://github.com/iziz/libPhoneNumber-iOS) port or even in the cpp variant of the [libphonenumber](https://github.com/google/libphonenumber) project.

2020-04-14 19:29 UTC, emostar commented
With that information, I agree. Can you just add a no-op, returning an empty string for iOS so the "getNameForNumber" method doesn't cause an exception to be raised?

2020-04-15 10:06 UTC, edwinnyawoli commented
Updated pull request with no op ios implementation

2020-10-02 03:44 UTC, emostar commented
@edwinnyawoli Sorry for dropping this, but I just came back and saw you added the no-op in. Thanks a lot for taking care of it!

I'll test this out and confirm everything is working, and then push a new version.

My biggest concern is having to keep this up to date, as the carrier library gets updated at least once a month with changes.

2020-10-02 07:48 UTC, emostar requested changes
Do you have a phone number that I can test with? My usual phone numbers are not returning any data for `getNameForNumber`.

We should also call it `getCaerrirNameForNumber` instead I think, as that is more explicit.

2020-10-02 07:48 UTC, emostar commented on android/src/main/java/com/codeheadlabs/libphonenumber/LibphonenumberPlugin.java
> +        handleGetNameForNumber(call, result);
You are missing a `break` here

2020-10-02 07:53 UTC, merged

2020-10-02 09:57 UTC, edwinnyawoli commented on android/src/main/java/com/codeheadlabs/libphonenumber/LibphonenumberPlugin.java
> +        handleGetNameForNumber(call, result);
Oops...Yeah I missed that. I'll correct that and update the pull request.